coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 1%

ignore:
  - api/app.py

comment:
  show_critical_paths: true

profiling:
  critical_files_paths:
    - api/calculator.py